__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'Chataq'

    from views import views

    app.register_blueprint(views, url_prefix='/')

    return app

app.py
from __init__ import create_app


app = create_app()

if __name__ == '__main__':
    app.run(debug=True)

views.py
import os
import sqlite3
from flask import Blueprint, render_template, request, jsonify
import matplotlib

matplotlib.use('Agg')
from matplotlib import pyplot as plt
import pandas as pd

views = Blueprint('views', __name__)


def get_categories_from_db():
    conn = sqlite3.connect('db/database.db')
    cursor = conn.cursor()
    cursor.execute('SELECT "Country/Region" FROM covid_data')
    countries = cursor.fetchall()
    conn.close()

    # Convert list of tuples to a set of strings
    countries_set = sorted(set(country[0] for country in countries))
    return countries_set


def read_data_from_db(db_file, table_name):
    conn = sqlite3.connect(db_file)
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    conn.close()
    return df


def save_plot_to_image(df_country, selected_countries):
    plt.figure()

    for country in selected_countries:
        if country in df_country.index:
            df_country.loc[country][1:].plot(label=country)

    plt.legend()
    plt.title('Covid-19 Cases for Selected Countries')
    plt.xlabel('Date')
    plt.ylabel('Total Cases')
    plt.grid(True)

    # Save plot as a PNG file
    image_path = '../Flask-DataAnalyze/static/images/covid_cases_plot.png'
    plt.savefig(image_path)
    plt.close()

    return 'images/covid_cases_plot.png'


@views.route('/', methods=['GET', 'POST'])
def index():
    db_file = "db/database.db"
    table_name = "covid_data"

    # Retrieve countries for dropdown
    countries = get_categories_from_db()

    if request.method == 'POST':
        # Get selected countries from the form
        country1 = request.form.get('country1')
        country2 = request.form.get('country2')

        # Read data from DB
        df = read_data_from_db(db_file, table_name)
        df.drop(["Lat", "Long"], axis=1, inplace=True)
        df_country = df.groupby("Country/Region").sum()

        # Generate plot based on selected countries
        plot_path = save_plot_to_image(df_country, [country1, country2])

        return render_template("index.html", countries=countries, plot=plot_path)

    return render_template("index.html", countries=countries)


@views.route('/tracker', methods=['GET', 'POST'])
def tracker():
    db_file = "db/database.db"
    table_name = "covid_data"

    search_value1 = request.args.get('search1', '').strip()
    search_value2 = request.args.get('search2', '').strip()

    plot_path = None

    if search_value1 and search_value2:
        df = read_data_from_db(db_file, table_name)
        df.drop(["Lat", "Long"], axis=1, inplace=True)
        df_country = df.groupby("Country/Region").sum()

        if search_value1 in df_country.index and search_value2 in df_country.index:
            plot_path = save_plot_to_image(df_country, [search_value1, search_value2])

    return render_template('tracker.html', plot=plot_path)


@views.route('/suggestions', methods=['GET'])
def suggestions():
    search_term = request.args.get('term', '').strip()
    db_file = "db/database.db"
    table_name = "covid_data"
    df = read_data_from_db(db_file, table_name)
    df.drop(["Lat", "Long"], axis=1, inplace=True)
    countries = df['Country/Region'].unique()

    # Filter countries based on search_term
    matches = [country for country in countries if search_term.lower() in country.lower()]

    return jsonify(matches)


@views.route('/plot', methods=['GET'])
def plot():
    country1 = request.args.get('country1')
    country2 = request.args.get('country2')

    db_file = "db/database.db"
    table_name = "covid_data"

    # Read data from DB
    df = read_data_from_db(db_file, table_name)
    df.drop(["Lat", "Long"], axis=1, inplace=True)
    df_country = df.groupby("Country/Region").sum()

    plot_path = save_plot_to_image(df_country, [country1, country2])

    if plot_path:
        return jsonify({'plot': plot_path})
    else:
        return jsonify({'error': 'Plot could not be generated'}), 400

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Data Analysis Dashboard{% endblock %}</title>
    <!-- Bootstrap css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
    />
</head>
<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top" data-bs-theme="dark">
    <div class="container-fluid">
        <a href="#" class="navbar-brand">Charts Data Analysis</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Link
                    </a>
                    <ul class="dropdown-menu">
                        {% for country in countries %}
                        <li><a class="dropdown-item" href="#">{{ country }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Link</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<!-- Main Content -->
<main class="container">
    <div>
        <form method="POST">
            <!-- 1st country -->
            <label for="country1">Select 1st country:</label>
            <select name="country1" id="country1">
                {% for country in countries %}
                <option value="{{ country }}">{{ country }}</option>
                {% endfor %}
            </select>

            <!-- 2nd country -->
            <label for="country2">Select 2nd country:</label>
            <select name="country2" id="country2">
                {% for country in countries %}
                <option value="{{ country }}">{{ country }}</option>
                {% endfor %}
            </select>

            <button type="submit">Generate!</button>
        </form>

        {% if plot %}
        <h2>Here is plot</h2>
        <img src="{{ url_for('static',filename=plot) }}" alt="Covid-19 Cases plot">
        {% endif %}
    </div>


    <h2>Statistics</h2>
    {% block dataframe %}
    <pre>{{ df }}</pre>
    <p>Detailed statistical analysis of the data.</p>
    {% endblock %}

    </section>

    <!--
    <section id="statistics2">
        <h2></h2>


        <p>Detailed statistical analysis of the data.</p>


    </section>
    <section id="statistics3">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="4">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="5">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>

    <section id="1">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="2">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="3">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="6">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="7">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>

    <section id="visualizations">
        <h2>Visualizations</h2>
        <p>Graphs and charts representing the data visually.</p>

    </section>

    <section id="reports">
        <h2>Reports</h2>
        <p>Download or view detailed reports.</p>

    </section>

    -->
</main>


<script
        type="text/javascript"
        src="{{ url_for('static', filename='js/scripts.js') }}"
></script>
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<!-- jQuery JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<!-- Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Data Analysis Dashboard{% endblock %}</title>
    <!-- Bootstrap css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
    />
</head>
<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top" data-bs-theme="dark">
    <div class="container-fluid">
        <a href="#" class="navbar-brand">Charts Data Analysis</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="{{ url_for('views.tracker') }}">Tracker</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Link
                    </a>
                    <ul class="dropdown-menu">
                        {% for country in countries %}
                        <li><a class="dropdown-item" href="#">{{ country }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Link</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<!-- Main Content -->
<main class="container">
    <div>
        <form method="POST">
            <!-- 1st country -->
            <label for="country1">Select 1st country:</label>
            <select name="country1" id="country1">
                {% for country in countries %}
                <option value="{{ country }}">{{ country }}</option>
                {% endfor %}
            </select>

            <!-- 2nd country -->
            <label for="country2">Select 2nd country:</label>
            <select name="country2" id="country2">
                {% for country in countries %}
                <option value="{{ country }}">{{ country }}</option>
                {% endfor %}
            </select>

            <button type="submit">Generate!</button>
        </form>

        {% if plot %}
        <h2>Here is plot</h2>
        <img src="{{ url_for('static',filename=plot) }}" alt="Covid-19 Cases plot">
        {% endif %}
    </div>

    <h2>Statistics</h2>
    {% block dataframe %}
    <pre>{{ df }}</pre>
    <p>Detailed statistical analysis of the data.</p>
    {% endblock %}

    </section>

    <!--
    <section id="statistics2">
        <h2></h2>


        <p>Detailed statistical analysis of the data.</p>


    </section>
    <section id="statistics3">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="4">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="5">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>

    <section id="1">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="2">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="3">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="6">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>
    <section id="7">
        <h2>Statistics</h2>
        <p>Detailed statistical analysis of the data.</p>

    </section>

    <section id="visualizations">
        <h2>Visualizations</h2>
        <p>Graphs and charts representing the data visually.</p>

    </section>

    <section id="reports">
        <h2>Reports</h2>
        <p>Download or view detailed reports.</p>

    </section>

    -->
</main>


<script
        type="text/javascript"
        src="{{ url_for('static', filename='js/scripts.js') }}"
></script>
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<!-- jQuery JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<!-- Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
</body>
</html>

templates/tracker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tracker</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
    <h1 class="text-center mb-4">Search and Plot</h1>

    <!-- Search Field 1 -->
    <div class="form-group">
        <label for="search1">Search 1:</label>
        <input type="text" id="search1" name="search1" class="form-control">
        <!-- Suggestions for Search Field 1 -->
        <div id="suggestions1" class="suggestions mt-2"></div>
    </div>

    <!-- Search Field 2 -->
    <div class="form-group">
        <label for="search2">Search 2:</label>
        <input type="text" id="search2" name="search2" class="form-control">
        <!-- Suggestions for Search Field 2 -->
        <div id="suggestions2" class="suggestions mt-2"></div>
    </div>

    <!-- Display Plot -->
    <h2 class="text-center mt-5">Generated Plot</h2>
    <div class="text-center">
        <img id="plot-image" src="" alt="Plot will be displayed here" class="img-fluid d-block mx-auto mt-3">
    </div>

    <div class="text-center mt-4">
        <a href="/" class="btn btn-dark">Back to Home</a>
    </div>
</div>

<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>